CC = g++
MKDIR = mkdir

SRCDIR = src
BUILDDIR = .
CFLAGS = -shared -fPIC -dynamiclib
INCLUDES = -I/System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers -I/Library/Frameworks/Python.framework/Versions/Current/Headers -I/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/Headers
LFLAGS = 
LIBS = -framework JavaVM -framework Python -framework CoreFoundation
MAIN = $(BUILDDIR)/libjavacallspython.dylib

all: $(MAIN)

$(MAIN):
	${MKDIR} -p $(BUILDDIR)
	$(CC) $(CFLAGS) $(INCLUDES) $(LFLAGS) $(LIBS) -o $(MAIN) $(SRCDIR)/ch_idsia_tools_amico_AmiCoJavaPy.cc

.PHONY: clean

clean:
	rm -f $(MAIN)

# DO NOT DELETE THIS LINE

